IF EXISTS 
	( 
	SELECT TABLE_NAME 
	FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_NAME = '[GenAgeMGIProteinsXGOTermsThreshold=7]' 
	)
DROP TABLE [GenAgeMGIProteinsXGOTermsThreshold=7]

CREATE TABLE [GenAgeMGIProteinsXGOTermsThreshold=7]
(
UniprotID VARCHAR(20),
ChildGOTermID1 VARCHAR(10),
GOTermName1 VARCHAR(255),
ChildGOTermID2 VARCHAR(10),
GOTermName2 VARCHAR(255),
ChildGOTermID3 VARCHAR(10),
GOTermName3 VARCHAR(255),
ChildGOTermID4 VARCHAR(10),
GOTermName4 VARCHAR(255),
ChildGOTermID5 VARCHAR(10),
GOTermName5 VARCHAR(255),
ChildGOTermID6 VARCHAR(10),
GOTermName6 VARCHAR(255),
ChildGOTermID7 VARCHAR(10),
GOTermName7 VARCHAR(255),
ChildGOTermID8 VARCHAR(10),
GOTermName8 VARCHAR(255),
ChildGOTermID9 VARCHAR(10),
GOTermName9 VARCHAR(255),
ChildGOTermID10 VARCHAR(10),
GOTermName10 VARCHAR(255),
ChildGOTermID11 VARCHAR(10),
GOTermName11 VARCHAR(255),
ChildGOTermID12 VARCHAR(10),
GOTermName12 VARCHAR(255),
ChildGOTermID13 VARCHAR(10),
GOTermName13 VARCHAR(255),
ChildGOTermID14 VARCHAR(10),
GOTermName14 VARCHAR(255),
ChildGOTermID15 VARCHAR(10),
GOTermName15 VARCHAR(255),
ChildGOTermID16 VARCHAR(10),
GOTermName16 VARCHAR(255)
)

INSERT INTO [GenAgeMGIProteinsXGOTermsThreshold=7]

SELECT DISTINCT a.UniprotID, b.* FROM tblProteinsXGOTerms a
JOIN [GenAgeMGIGOTermHierarchyThreshold=7] b ON b.ChildGOTermID = a.GOTermID
ORDER BY a.UniprotID, b.ChildGOTermID